sudo: required

services:
  - docker
script:
  - docker pull mdavezac/pylada-light
  - sudo docker run -it -v $(pwd):/project -w /project --cap-add SYS_PTRACE mdavezac/pylada-light python3 -m pip install -e .
  - sudo docker run -it -v $(pwd):/project -w /project --cap-add SYS_PTRACE mdavezac/pylada-light python3 -c "from pylada import tests; test()"

notifications:
  slack:
    matrix:
    - pylada:J4ytpqLv9KJqG18zAnENZVRL
    rooms:
      secure: HjsbOCT//OjseJlfoomf/QiMVDbkpOjicy4u9Gd23yKcImCKuZTs9nzgmOK5yN7rdaoVQ+ewbKY+6knZLrLlsuvC3ElPaw2rOdqSXoohVltvBxiBaIFm/EdAqXxK0mebfY2JCNbJEK//AnAqZcxPs/OVKRUF1pLhVPM6ZvrK7ic=
