language: cpp
compiler:
  - gcc
  - clang
python:
  - "2.6"
  - "2.7"
install:
  - pip install numpy
  - pip install scipy
  - pip install quantities
  - pip install ipython
script: 
  - mkdir build
  - cd build 
  - cmake -Dexternal_program_tests=OFF ..
  - make
branches:
  only:
    - cmake
os:
  - osx
  - linux
