sudo: required

services:
  - docker
script:
  - .travis/install_from_pip.sh

notifications:
  slack:
    matrix:
    - pylada:J4ytpqLv9KJqG18zAnENZVRL
    rooms:
      secure: HjsbOCT//OjseJlfoomf/QiMVDbkpOjicy4u9Gd23yKcImCKuZTs9nzgmOK5yN7rdaoVQ+ewbKY+6knZLrLlsuvC3ElPaw2rOdqSXoohVltvBxiBaIFm/EdAqXxK0mebfY2JCNbJEK//AnAqZcxPs/OVKRUF1pLhVPM6ZvrK7ic=
