sudo: required

services:
  - docker
script:
  - source .docker/pylada.sh && pylada setup gcc -DPYTHON_EXECUTABLE=python3 -DCMAKE_BUILD_TYPE=Release
  - source .docker/pylada.sh && pylada build gcc lookup_dependencies
  - source .docker/pylada.sh && pylada build gcc
  - source .docker/pylada.sh && pylada test gcc -V
  - source .docker/pylada.sh && pylada cmd gcc ../.install_from_pip.sh

notifications:
  slack:
    matrix:
    - pylada:J4ytpqLv9KJqG18zAnENZVRL
    rooms:
      secure: HjsbOCT//OjseJlfoomf/QiMVDbkpOjicy4u9Gd23yKcImCKuZTs9nzgmOK5yN7rdaoVQ+ewbKY+6knZLrLlsuvC3ElPaw2rOdqSXoohVltvBxiBaIFm/EdAqXxK0mebfY2JCNbJEK//AnAqZcxPs/OVKRUF1pLhVPM6ZvrK7ic=
